name: S3 Credential Heartbeat

on:
  schedule:
    - cron: '0 08 * * *' # Runs every day at 08:00 UTC
  workflow_dispatch: # Trigger S3 credentials manually from the UI

jobs:
  check-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Check S3 Connectivity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          # See if the token is still valid
          aws s3 ls s3://ibc-sales-data-579747662833/ --summarize